In [1]:
import numpy as np
import h5py

In [2]:
# Helper function to help read the h5 files.
def simple_read_data(fileName):
    print(fileName)
    hf = h5py.File('{}.h5'.format(fileName), 'r')
    
    # We'll return a dictionary object. 
    results = {}
    
    results['rs_glob_acc'] = np.array(hf.get('rs_glob_acc')[:])
    results['rs_train_acc'] = np.array(hf.get('rs_train_acc')[:])
    results['rs_train_loss'] = np.array(hf.get('rs_train_loss')[:])
    
    # 3D array: Read as [number of times, number of epochs, number of users].
    results['perUserAccs'] = np.array(hf.get('perUserAccs'))
    
    return results

### Datasplit-1

In [5]:
# Define the global directory path.
directoryPath = '/home/adgdri/pFedMe/results/'

### DS-1 Latest attempts.

In [18]:
fileNames = [
    'Mnist_PerAvg_p_0.001_0.001_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.001_0.001_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.99]

 Average accuracy across all the different runs : 0.990000.

 Average per user accuracy averaged over different runs: 
 [[0.9917]
 [1.    ]
 [1.    ]
 [1.    ]
 [0.9917]
 [0.9917]
 [0.9833]
 [0.9833]
 [0.975 ]
 [0.9833]].

 Per-user averaged accuracy: 
 0.990000.


In [6]:
fileNames = [
    'Mnist_PerAvg_p_0.001_0.0025_15_10u_128b_20_0_roundNum_0_globalIters_1000_dataSplit_1'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.001_0.0025_15_10u_128b_20_0_roundNum_0_globalIters_1000_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.9425]

 Average accuracy across all the different runs : 0.942500.

 Average per user accuracy averaged over different runs: 
 [[1.    ]
 [1.    ]
 [1.    ]
 [1.    ]
 [0.9833]
 [1.    ]
 [0.525 ]
 [0.9667]
 [0.9667]
 [0.9833]].

 Per-user averaged accuracy: 
 0.942500.


In [7]:
fileNames = [
    'Mnist_PerAvg_p_0.001_0.005_15_10u_128b_20_0_roundNum_0_globalIters_1000_dataSplit_1'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.001_0.005_15_10u_128b_20_0_roundNum_0_globalIters_1000_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.8608333333333333]

 Average accuracy across all the different runs : 0.860833.

 Average per user accuracy averaged over different runs: 
 [[1.    ]
 [1.    ]
 [1.    ]
 [1.    ]
 [0.875 ]
 [0.9667]
 [0.5083]
 [1.    ]
 [0.7833]
 [0.475 ]].

 Per-user averaged accuracy: 
 0.860830.


In [8]:
fileNames = [
    'Mnist_PerAvg_p_0.001_0.0075_15_10u_128b_20_0_roundNum_0_globalIters_1000_dataSplit_1'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.001_0.0075_15_10u_128b_20_0_roundNum_0_globalIters_1000_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.7533333333333333]

 Average accuracy across all the different runs : 0.753333.

 Average per user accuracy averaged over different runs: 
 [[0.9917]
 [0.9917]
 [0.525 ]
 [0.975 ]
 [0.8667]
 [0.95  ]
 [0.5083]
 [0.675 ]
 [0.525 ]
 [0.525 ]].

 Per-user averaged accuracy: 
 0.753340.


In [9]:
fileNames = [
    'Mnist_PerAvg_p_0.001_0.01_15_10u_128b_20_0_roundNum_0_globalIters_1000_dataSplit_1'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.001_0.01_15_10u_128b_20_0_roundNum_0_globalIters_1000_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.8658333333333333]

 Average accuracy across all the different runs : 0.865833.

 Average per user accuracy averaged over different runs: 
 [[0.9917]
 [0.975 ]
 [0.9417]
 [0.9667]
 [0.95  ]
 [0.8833]
 [0.8083]
 [0.4667]
 [0.9833]
 [0.6917]].

 Per-user averaged accuracy: 
 0.865840.


### DS-1

In [27]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.18333333333333332]

 Average accuracy across all the different runs : 0.183333.

 Average per user accuracy averaged over different runs: 
 [[0.4083]
 [0.    ]
 [0.    ]
 [0.5167]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.4583]
 [0.45  ]
 [0.    ]].

 Per-user averaged accuracy: 
 0.183330.


In [31]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.0075_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.0075_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.18333333333333332]

 Average accuracy across all the different runs : 0.183333.

 Average per user accuracy averaged over different runs: 
 [[0.4083]
 [0.    ]
 [0.    ]
 [0.5167]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.4583]
 [0.45  ]
 [0.    ]].

 Per-user averaged accuracy: 
 0.183330.


In [30]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.005_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.005_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.18333333333333332]

 Average accuracy across all the different runs : 0.183333.

 Average per user accuracy averaged over different runs: 
 [[0.4083]
 [0.    ]
 [0.    ]
 [0.5167]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.4583]
 [0.45  ]
 [0.    ]].

 Per-user averaged accuracy: 
 0.183330.


In [29]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.0025_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.0025_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.18333333333333332]

 Average accuracy across all the different runs : 0.183333.

 Average per user accuracy averaged over different runs: 
 [[0.4083]
 [0.    ]
 [0.    ]
 [0.5167]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.4583]
 [0.45  ]
 [0.    ]].

 Per-user averaged accuracy: 
 0.183330.


In [28]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.18333333333333332]

 Average accuracy across all the different runs : 0.183333.

 Average per user accuracy averaged over different runs: 
 [[0.4083]
 [0.    ]
 [0.    ]
 [0.5167]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.4583]
 [0.45  ]
 [0.    ]].

 Per-user averaged accuracy: 
 0.183330.


### DS-2

In [9]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_2'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_2
----------------------------------------

 Average accuracies across all the users over different runs : [0.8823931040368695]

 Average accuracy across all the different runs : 0.882393.

 Average per user accuracy averaged over different runs: 
 [[0.9083]
 [0.8579]
 [0.8547]
 [0.8859]
 [0.884 ]
 [0.9128]
 [0.8798]
 [0.8848]
 [0.8583]
 [0.8912]].

 Per-user averaged accuracy: 
 0.881770.


In [10]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.0075_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_2'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.0075_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_2
----------------------------------------

 Average accuracies across all the users over different runs : [0.8806008363915678]

 Average accuracy across all the different runs : 0.880601.

 Average per user accuracy averaged over different runs: 
 [[0.9083]
 [0.8566]
 [0.8529]
 [0.8845]
 [0.8792]
 [0.9091]
 [0.8816]
 [0.8907]
 [0.8571]
 [0.882 ]].

 Per-user averaged accuracy: 
 0.880200.


In [12]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.005_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_2'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.005_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_2
----------------------------------------

 Average accuracies across all the users over different runs : [0.8784671844328753]

 Average accuracy across all the different runs : 0.878467.

 Average per user accuracy averaged over different runs: 
 [[0.9013]
 [0.8662]
 [0.8555]
 [0.8749]
 [0.8749]
 [0.91  ]
 [0.8835]
 [0.8863]
 [0.8532]
 [0.8843]].

 Per-user averaged accuracy: 
 0.879010.


In [13]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.0025_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_2'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.0025_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_2
----------------------------------------

 Average accuracies across all the users over different runs : [0.8727489971835795]

 Average accuracy across all the different runs : 0.872749.

 Average per user accuracy averaged over different runs: 
 [[0.8904]
 [0.8552]
 [0.8477]
 [0.8646]
 [0.8749]
 [0.9063]
 [0.8751]
 [0.8878]
 [0.8481]
 [0.8855]].

 Per-user averaged accuracy: 
 0.873560.


### DS-3

In [16]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_3'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_3
----------------------------------------

 Average accuracies across all the users over different runs : [0.972674473959821]

 Average accuracy across all the different runs : 0.972674.

 Average per user accuracy averaged over different runs: 
 [[0.9861]
 [0.9759]
 [0.961 ]
 [0.9603]
 [0.9672]
 [0.9735]
 [0.9801]
 [0.9664]
 [0.9799]
 [0.9719]].

 Per-user averaged accuracy: 
 0.972230.


In [17]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.0075_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_3'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.0075_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_3
----------------------------------------

 Average accuracies across all the users over different runs : [0.971055888793678]

 Average accuracy across all the different runs : 0.971056.

 Average per user accuracy averaged over different runs: 
 [[0.9872]
 [0.9737]
 [0.9587]
 [0.9582]
 [0.9684]
 [0.9719]
 [0.9793]
 [0.9636]
 [0.9782]
 [0.9678]].

 Per-user averaged accuracy: 
 0.970700.


In [18]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.005_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_3'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.005_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_3
----------------------------------------

 Average accuracies across all the users over different runs : [0.9684851947062744]

 Average accuracy across all the different runs : 0.968485.

 Average per user accuracy averaged over different runs: 
 [[0.984 ]
 [0.9716]
 [0.9552]
 [0.9528]
 [0.9636]
 [0.9712]
 [0.9793]
 [0.9627]
 [0.974 ]
 [0.9654]].

 Per-user averaged accuracy: 
 0.967980.


In [19]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.0025_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_3'
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.0025_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_3
----------------------------------------

 Average accuracies across all the users over different runs : [0.9664857659716272]

 Average accuracy across all the different runs : 0.966486.

 Average per user accuracy averaged over different runs: 
 [[0.984 ]
 [0.9683]
 [0.9518]
 [0.9475]
 [0.96  ]
 [0.9735]
 [0.9768]
 [0.9591]
 [0.9707]
 [0.9662]].

 Per-user averaged accuracy: 
 0.965790.


#### Num Epochs: 25

In [11]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_25_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_25_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_25_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_25_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_25_dataSplit_1',
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_25_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_25_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_25_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_25_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_25_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.9966666666666667, 0.9891666666666666, 0.9891666666666666, 0.9866666666666667, 0.9941666666666666]

 Average accuracy across all the different runs : 0.991167.

 Average per user accuracy averaged over different runs: 
 [[0.99  ]
 [0.9983]
 [0.9833]
 [0.985 ]
 [0.99  ]
 [0.99  ]
 [0.9967]
 [0.9983]
 [0.99  ]
 [0.99  ]].

 Per-user avera

#### Num Epochs: 50

In [12]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_50_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_50_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_50_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_50_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_50_dataSplit_1',
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_50_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_50_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_50_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_50_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_50_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.9891666666666666, 0.9908333333333333, 0.9925, 0.9908333333333333, 0.9958333333333333]

 Average accuracy across all the different runs : 0.991833.

 Average per user accuracy averaged over different runs: 
 [[0.9883]
 [0.9983]
 [0.9967]
 [0.985 ]
 [0.9917]
 [0.9917]
 [0.995 ]
 [0.9933]
 [0.9883]
 [0.99  ]].

 Per-user averaged accuracy

#### Num Epochs: 100

In [13]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_100_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_100_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_100_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_100_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_100_dataSplit_1',
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_100_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_100_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_100_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_100_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_100_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.9875, 0.9908333333333333, 0.9891666666666666, 0.9941666666666666, 0.9958333333333333]

 Average accuracy across all the different runs : 0.991500.

 Average per user accuracy averaged over different runs: 
 [[0.99  ]
 [0.9883]
 [0.9983]
 [0.9867]
 [0.995 ]
 [0.9883]
 [0.995 ]
 [1.    ]
 [0.9867]
 [0.9867]].

 Per-user averaged acc

#### Num Epochs: 150

In [14]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_150_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_150_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_150_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_150_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_150_dataSplit_1',
]
# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_150_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_150_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_150_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_150_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_150_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.9958333333333333, 0.9933333333333333, 0.9975, 0.9933333333333333, 0.9958333333333333]

 Average accuracy across all the different runs : 0.995167.

 Average per user accuracy averaged over different runs: 
 [[0.9917]
 [0.9967]
 [0.9983]
 [0.99  ]
 [0.9933]
 [0.9967]
 [0.995 ]
 [0.9983]
 [0.9933]
 [0.9983]].

 Per-user averaged acc

#### Num Epochs: 200

In [15]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_200_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_200_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_200_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_200_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_200_dataSplit_1',
]

# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_200_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_200_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_200_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_200_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_200_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.9975, 0.9916666666666667, 0.995, 0.9941666666666666, 0.9966666666666667]

 Average accuracy across all the different runs : 0.995000.

 Average per user accuracy averaged over different runs: 
 [[0.995 ]
 [0.9967]
 [0.9983]
 [0.99  ]
 [0.9933]
 [0.995 ]
 [0.9967]
 [0.9983]
 [0.99  ]
 [0.9967]].

 Per-user averaged accuracy: 
 0.99

#### Num Epochs: 300

In [16]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_300_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_300_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_300_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_300_dataSplit_1',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_300_dataSplit_1',
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_300_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_300_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_300_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_300_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_300_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.9941666666666666, 0.99, 0.9958333333333333, 0.9941666666666666, 0.9975]

 Average accuracy across all the different runs : 0.994333.

 Average per user accuracy averaged over different runs: 
 [[0.995 ]
 [0.995 ]
 [1.    ]
 [0.9867]
 [0.9933]
 [0.995 ]
 [0.9933]
 [1.    ]
 [0.9933]
 [0.9917]].

 Per-user averaged accuracy: 
 0.994

### Datasplit-2

In [17]:
# Define the global directory path.
directoryPath = '/home/adgdri/pFedMe/results/'

#### Num Epochs: 25

In [18]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_25_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_25_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_25_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_25_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_25_dataSplit_2',
]

# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_25_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_25_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_25_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_25_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_25_dataSplit_2
----------------------------------------

 Average accuracies across all the users over different runs : [0.1899112325025606, 0.2224972262524537, 0.1870626386755419, 0.18443287530937955, 0.21991807475678443]

 Average accuracy across all the different runs : 0.200764.

 Average per user accuracy averaged over different runs: 
 [[0.2245]
 [0.1798]
 [0.2219]
 [0.1778]
 [0.191 ]
 [0.2351]
 [0.1794]
 [0.2023]
 [0.1883]
 [0.1785]].

 Per-user ave

#### Num Epochs: 50

In [19]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_50_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_50_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_50_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_50_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_50_dataSplit_2',
]

# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_50_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_50_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_50_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_50_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_50_dataSplit_2
----------------------------------------

 Average accuracies across all the users over different runs : [0.21526118129054284, 0.25083212426389007, 0.2019969278033794, 0.2388836732952121, 0.2667690732206861]

 Average accuracy across all the different runs : 0.234749.

 Average per user accuracy averaged over different runs: 
 [[0.2869]
 [0.2441]
 [0.2264]
 [0.2494]
 [0.2228]
 [0.2581]
 [0.2003]
 [0.221 ]
 [0.2204]
 [0.1906]].

 Per-user ave

#### Num Epochs: 100

In [20]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_100_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_100_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_100_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_100_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_100_dataSplit_2',
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_100_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_100_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_100_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_100_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_100_dataSplit_2
----------------------------------------

 Average accuracies across all the users over different runs : [0.22388187094571527, 0.26773064777673466, 0.23724185014507596, 0.25211231543910556, 0.2767537122375832]

 Average accuracy across all the different runs : 0.251544.

 Average per user accuracy averaged over different runs: 
 [[0.3032]
 [0.2701]
 [0.2328]
 [0.2753]
 [0.2292]
 [0.2921]
 [0.2139]
 [0.2355]
 [0.2282]
 [0.2119]].

 Per-u

#### Num Epochs: 200

In [21]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_200_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_200_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_200_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_200_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_200_dataSplit_2',
]


# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_200_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_200_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_200_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_200_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_200_dataSplit_2
----------------------------------------

 Average accuracies across all the users over different runs : [0.22243086377603277, 0.27293675855594435, 0.24159412869090288, 0.26781599385508237, 0.27863116572793994]

 Average accuracy across all the different runs : 0.256682.

 Average per user accuracy averaged over different runs: 
 [[0.3126]
 [0.2569]
 [0.2554]
 [0.2674]
 [0.2489]
 [0.2964]
 [0.2366]
 [0.2254]
 [0.2272]
 [0.2029]].

 Per-

## Datasplit-3

In [22]:
# Define the global directory path.
directoryPath = '/home/adgdri/pFedMe/results/'

#### Num Epochs: 25

In [23]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_25_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_25_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_25_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_25_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_25_dataSplit_3',
]

# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_25_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_25_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_25_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_25_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_25_dataSplit_3
----------------------------------------

 Average accuracies across all the users over different runs : [0.4003809523809524, 0.4108180173316827, 0.3916769831444624, 0.4003809523809524, 0.39895238095238095]

 Average accuracy across all the different runs : 0.400442.

 Average per user accuracy averaged over different runs: 
 [[0.4018]
 [0.3482]
 [0.3685]
 [0.5184]
 [0.3786]
 [0.3954]
 [0.477 ]
 [0.3842]
 [0.4039]
 [0.3674]].

 Per-user aver

#### Num Epochs: 50

In [24]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_50_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_50_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_50_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_50_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_50_dataSplit_3',
]

# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_50_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_50_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_50_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_50_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_50_dataSplit_3
----------------------------------------

 Average accuracies across all the users over different runs : [0.3919047619047619, 0.37196457480239975, 0.3758689648604895, 0.3920952380952381, 0.38123809523809526]

 Average accuracy across all the different runs : 0.382614.

 Average per user accuracy averaged over different runs: 
 [[0.3824]
 [0.365 ]
 [0.3836]
 [0.4777]
 [0.3732]
 [0.3763]
 [0.4672]
 [0.358 ]
 [0.3219]
 [0.3695]].

 Per-user ave

#### Num Epochs: 100

In [25]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_100_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_100_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_100_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_100_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_100_dataSplit_3',
]

# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_0_globalIters_100_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_1_globalIters_100_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_2_globalIters_100_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_3_globalIters_100_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.001_15_10u_128b_20_avg_roundNum_4_globalIters_100_dataSplit_3
----------------------------------------

 Average accuracies across all the users over different runs : [0.39876190476190476, 0.406913627273593, 0.3721550328540139, 0.3994285714285714, 0.382]

 Average accuracy across all the different runs : 0.391852.

 Average per user accuracy averaged over different runs: 
 [[0.3985]
 [0.3386]
 [0.3838]
 [0.5042]
 [0.3757]
 [0.3847]
 [0.4454]
 [0.3813]
 [0.3769]
 [0.3662]].

 Per-user averaged accu

### Datasplit-1

In [20]:
fileNames = [
    'Mnist_PerAvg_p_0.001_0.001_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1',
    'Mnist_PerAvg_p_0.001_0.001_15_10u_128b_20_0_roundNum_1_globalIters_800_dataSplit_1',
    'Mnist_PerAvg_p_0.001_0.001_15_10u_128b_20_0_roundNum_2_globalIters_800_dataSplit_1',
    'Mnist_PerAvg_p_0.001_0.001_15_10u_128b_20_0_roundNum_3_globalIters_800_dataSplit_1',
    'Mnist_PerAvg_p_0.001_0.001_15_10u_128b_20_0_roundNum_4_globalIters_800_dataSplit_1',
]

# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.001_0.001_15_10u_128b_20_0_roundNum_0_globalIters_800_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.001_0.001_15_10u_128b_20_0_roundNum_1_globalIters_800_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.001_0.001_15_10u_128b_20_0_roundNum_2_globalIters_800_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.001_0.001_15_10u_128b_20_0_roundNum_3_globalIters_800_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.001_0.001_15_10u_128b_20_0_roundNum_4_globalIters_800_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.99, 0.99, 0.9966666666666667, 0.9766666666666667, 0.9916666666666667]

 Average accuracy across all the different runs : 0.989000.

 Average per user accuracy averaged over different runs: 
 [[0.9733]
 [0.99  ]
 [0.9967]
 [0.9867]
 [0.99  ]
 [0.9883]
 [0.9917]
 [0.9933]
 [0.9883]
 [0.9917]].

 Per-user averaged accuracy: 
 0.989000.


### Datasplit-2

In [22]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_1_globalIters_800_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_2_globalIters_800_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_3_globalIters_800_dataSplit_2',
    'Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_4_globalIters_800_dataSplit_2',
]

# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)


print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_1_globalIters_800_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_2_globalIters_800_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_3_globalIters_800_dataSplit_2
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_4_globalIters_800_dataSplit_2
----------------------------------------

 Average accuracies across all the users over different runs : [0.8823931040368695, 0.8708080894274256, 0.8724076128701886, 0.875405359276327, 0.8741252773510838]

 Average accuracy across all the different runs : 0.875028.

 Average per user accuracy averaged over different runs: 
 [[0.875 ]
 [0.8613]
 [0.8622]
 [0.8746]
 [0.8804]
 [0.8681]
 [0.8789]
 [0.8821]
 [0.8851]
 [0.8907]].

 Per-user averag

### Datasplit-3

In [9]:
# Define the global directory path.
directoryPath = '/home/adgdri/pFedMe/results/tempResults/'

In [10]:
fileNames = [
    'Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_1_globalIters_800_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_2_globalIters_800_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_3_globalIters_800_dataSplit_3',
    'Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_4_globalIters_800_dataSplit_3',
]

# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)

print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/tempResults/Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_0_globalIters_800_dataSplit_3
/home/adgdri/pFedMe/results/tempResults/Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_1_globalIters_800_dataSplit_3
/home/adgdri/pFedMe/results/tempResults/Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_2_globalIters_800_dataSplit_3
/home/adgdri/pFedMe/results/tempResults/Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_3_globalIters_800_dataSplit_3
/home/adgdri/pFedMe/results/tempResults/Mnist_PerAvg_p_0.01_0.01_15_10u_128b_20_avg_roundNum_4_globalIters_800_dataSplit_3
----------------------------------------

 Average accuracies across all the users over different runs : [0.972674473959821, 0.9715319432543083, 0.9754332508093696, 0.969053513616454, 0.9756236907255761]

 Average accuracy across all the different runs : 0.972863.

 Average per user accuracy averaged over different runs: 
 [[0.9859]
 [0.9764]
 [0.9677]
 [0.9595]
 [0.9712]
 [0.9773]


### MNIST pFedMe paper check

In [5]:
fileNames = [
    'Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_0_globalIters_800_dataSplit_3',
    'Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_1_globalIters_800_dataSplit_3',
    'Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_2_globalIters_800_dataSplit_3',
    'Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_3_globalIters_800_dataSplit_3',
    'Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_4_globalIters_800_dataSplit_3',
]

# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)

print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_0_globalIters_800_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_1_globalIters_800_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_2_globalIters_800_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_3_globalIters_800_dataSplit_3
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_4_globalIters_800_dataSplit_3
----------------------------------------

 Average accuracies across all the users over different runs : [0.9724840521755689, 0.9691516709511568, 0.9726718720243763, 0.966006474957151, 0.9738145115216149]

 Average accuracy across all the different runs : 0.970826.

 Average per user accuracy averaged over different runs: 
 [[0.9851]
 [0.9742]
 [0.9642]
 [0.9531]
 [0.9697]
 [0.9768]
 [0.982 ]
 [0.9656]
 [0.9625]
 [0.9723]].

 Per-user averag

In [7]:
fileNames = [
    'Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_0_globalIters_800_dataSplit_1',
    'Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_1_globalIters_800_dataSplit_1',
    'Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_2_globalIters_800_dataSplit_1',
    'Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_3_globalIters_800_dataSplit_1',
    'Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_4_globalIters_800_dataSplit_1',
]

# Get the number of users.
numUsers = int(fileNames[0].split('u')[0].split('_')[-1])

avgPersAcc = []
perUserAcc = np.zeros((1, numUsers))

for fileName in fileNames:
    ob = simple_read_data(directoryPath + fileName)
    avgPersAcc.append( ob['rs_glob_acc'][-1] )
    # Take the per user accuracy from the last epoch.
    perUserAcc += ob['perUserAccs'][:,-1,:]

# Average out over the different runs.
perUserAcc /= len(fileNames)

print ('----------------------------------------')

print ('\n Average accuracies across all the users over different runs : %s' % avgPersAcc)

print ('\n Average accuracy across all the different runs : %f.' % np.mean(avgPersAcc) )

print ('\n Average per user accuracy averaged over different runs: \n %s.' % np.round(perUserAcc.T, 4))

print ('\n Per-user averaged accuracy: \n %f.' % np.mean(np.round(perUserAcc.T, 4))) 

/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_0_globalIters_800_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_1_globalIters_800_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_2_globalIters_800_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_3_globalIters_800_dataSplit_1
/home/adgdri/pFedMe/results/Mnist_PerAvg_p_0.02_0.001_15_10u_20b_20_avg_roundNum_4_globalIters_800_dataSplit_1
----------------------------------------

 Average accuracies across all the users over different runs : [0.18333333333333332, 0.14083333333333334, 0.2125, 0.18916666666666668, 0.18833333333333332]

 Average accuracy across all the different runs : 0.182833.

 Average per user accuracy averaged over different runs: 
 [[0.0817]
 [0.1067]
 [0.    ]
 [0.3033]
 [0.1033]
 [0.0883]
 [0.275 ]
 [0.3667]
 [0.29  ]
 [0.2133]].

 Per-user averaged accu